# Generated by Django 4.2.20 on 2025-03-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('oracle_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Oracle ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sold_hours', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sold Hours')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('tandm', 'T&M'), ('cu', 'CU'), ('pp', 'Pre Paied')], default='tandm', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureItem',
            fields=[
                ('trans_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Trans Id')),
                ('task', models.CharField(max_length=5, verbose_name='Task')),
                ('expnd_type', models.CharField(max_length=55, verbose_name='Expnd Type')),
                ('item_date', models.DateField(verbose_name='Item Date')),
                ('employee_supplier', models.CharField(max_length=255, verbose_name='Employee/Supplier')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('uom', models.CharField(max_length=55, verbose_name='UOM')),
                ('proj_func_burdened_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Proj Func Burdened Cost')),
                ('project_burdened_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Project Burdened Cost')),
                ('accrued_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Accrued Revenue')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bill Amount')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='Comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmb.project')),
            ],
        ),
    ]
