# Generated by Django 4.2.20 on 2025-04-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_imported',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('task', models.CharField(max_length=5, verbose_name='Task')),
                ('name', models.CharField(choices=[('na', 'Not assigned'), ('pc', 'Project Coordinator'), ('pm', 'Project Manager'), ('spm', 'Senior Project Manager'), ('arc', 'Architect'), ('sarc', 'Senior Architect'), ('con', 'Consultant'), ('scon', 'Senior Consultant')], default='--', max_length=6)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sold Hours')),
                ('sold_hours', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sold Hours')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmb.project')),
            ],
        ),
    ]
