# Generated by Django 4.2.20 on 2025-05-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vmb", "0002_project_last_imported_milestone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Time_Sheet_Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="timesheets")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(upload_to="expenditures"),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="cost_per_hour",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Cost per Hour"
            ),
        ),
        migrations.CreateModel(
            name="Timecards",
            fields=[
                (
                    "timecard_id",
                    models.CharField(max_length=28, primary_key=True, serialize=False),
                ),
                ("start_date", models.DateField()),
                ("name", models.CharField(max_length=255, verbose_name="Full Name")),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Hours"
                    ),
                ),
                (
                    "deliver_location",
                    models.CharField(max_length=25, verbose_name="Delivery Location"),
                ),
                ("team", models.CharField(max_length=5, verbose_name="Team")),
                ("notes", models.CharField(max_length=512, verbose_name="Notes")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vmb.milestone"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vmb.project"
                    ),
                ),
            ],
        ),
    ]
