# Generated by Django 4.2.20 on 2025-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmb", "0003_time_sheet_document_alter_project_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimecardDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="timecards")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Document",
            new_name="ExpenditureDocument",
        ),
        migrations.RenameModel(
            old_name="Timecards",
            new_name="TimecardItems",
        ),
        migrations.DeleteModel(
            name="Time_Sheet_Document",
        ),
    ]
