# Generated by Django 4.2.20 on 2025-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmb", "0004_timecarddocument_rename_document_expendituredocument_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timecarditems",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
    ]
