# Generated by Django 4.2.20 on 2025-05-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmb", "0005_alter_timecarditems_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timecarditems",
            name="created",
        ),
        migrations.RemoveField(
            model_name="timecarditems",
            name="modified",
        ),
    ]
