# Generated by Django 4.2.20 on 2025-06-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vmb", "0006_remove_timecarditems_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project_Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
        ),
        migrations.AlterField(
            model_name="milestone",
            name="name",
            field=models.CharField(
                choices=[
                    ("na", "Not assigned"),
                    ("pc", "Project Coordinator"),
                    ("pm", "Project Manager"),
                    ("spm", "Senior Project Manager"),
                    ("arc", "Architect"),
                    ("sarc", "Senior Architect"),
                    ("con", "Consultant"),
                    ("scon", "Senior Consultant"),
                    ("prarc", "Principal Architect"),
                    ("el", "Engagement Lead"),
                    ("fpe", "Fixed Price Engagement"),
                ],
                default="--",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vmb.project_group",
            ),
        ),
    ]
